vm_name        = "xpay-vm01"
location       = "Central India"
resource_group = "rg-xpay-dev"
vm_size        = "Standard_B2s"
nic_id         = "/subscriptions/XXXX/resourceGroups/rg-network/providers/Microsoft.Network/networkInterfaces/nic01"
ssh_public_key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILrLozOTzzNS4y75aS7kojqwWieYrX4AXX2GU1jCMURr azureadmin@TerraformVM"